apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: authors
spec:
  hosts:
    - authors
  http:
    - fault:
        delay:
          fixedDelay: 40s
          percentage:
            value: 100
      route:
        - destination:
            host: authors